"""Narration for the Power BI MCP setup guide video, scene by scene.

Each line is (beat_id, caption) or (beat_id, caption, spoken). `spoken` overrides what the voice says when the
caption text would be read badly (file names, URLs, .pbix and so on). Beat ids are referenced by template.html.
"""

SCENES = [
    ("intro", "Power BI MCP for Claude", [
        ("i1", "Welcome! In this video you'll set up Power BI MCP for Claude, from downloading the kit to building your first dashboard."),
        ("i2", "Once it's set up, Claude can read your Power BI model, answer questions with DAX, write measures and build whole dashboard pages for you."),
        ("i3", "It takes about 10 minutes, and you only do it once. Let's start."),
    ]),
    ("need", "What you need", [
        ("n1", "First, here's what you need."),
        ("n2", "A Windows 10 or 11 computer, because Power BI Desktop only runs on Windows."),
        ("n3", "Power BI Desktop. The normal download from Microsoft works best."),
        ("n4", "Python 3.12. We'll install it together in a minute."),
        ("n5", "And Claude Desktop, installed and signed in. Get it from claude.ai/download.",
               "And Claude Desktop, installed and signed in. Get it from claude dot A I, slash download."),
    ]),
    ("page", "Step 1 · Open your download page", [
        ("p1", "Step 1. Open your browser and go to powerbi.growora.live/purchase.html",
               "Step one. Open your browser and go to power B I dot growora dot live, slash purchase dot H T M L."),
        ("p2", "This is the buyers' page. It asks for two things: the email you paid with, and your payment ID."),
    ]),
    ("pid", "Step 1 · Find your payment ID", [
        ("q1", "Where's the payment ID? Open the inbox of the email you used to pay."),
        ("q2", "Easiest: open our email \"Your Power BI MCP for Claude download\" and click Open my download page. Everything is filled in for you.",
               "The easiest way: open our email, Your Power B I MCP for Claude download, and click, Open my download page. Everything is filled in for you."),
        ("q3", "Or open Razorpay's receipt email and copy the Payment ID. It always starts with pay_",
               "Or open Razorpay's receipt email, and copy the Payment I D. It always starts with, pay underscore."),
        ("q4", "Can't see either email? Check Spam and Promotions, or search your inbox for Razorpay."),
    ]),
    ("verify", "Step 1 · Verify and download", [
        ("v1", "Type your email, paste the payment ID, and click Verify and open downloads.",
               "Type your email, paste the payment I D, and click, Verify and open downloads."),
        ("v2", "The page checks your purchase with Razorpay. In a few seconds you'll see: You're in. Thank you!"),
        ("v3", "Now download both files: the Power BI MCP kit (powerbi-mcp.zip) and the PDF guide.",
               "Now download both files: the Power B I MCP kit, which is a zip file, and the P D F guide."),
        ("v4", "These links work for 24 hours. Come back to this page any time for fresh links."),
    ]),
    ("python", "Step 2 · Install Python 3.12", [
        ("y1", "Step 2. Install Python 3.12.", "Step two. Install Python 3.12."),
        ("y2", "Go to python.org, open the Python 3.12 release and download the Windows installer (64-bit).",
               "Go to python dot org, open the Python 3.12 release, and download the Windows installer, 64 bit."),
        ("y3", "Run it. On the first screen, tick Add python.exe to PATH. This is important! Then click Install Now.",
               "Run it. On the first screen, tick, Add python dot exe to PATH. This is important! Then click, Install Now."),
        ("y4", "Already have a newer Python, like 3.13? That's fine. Install 3.12 next to it. Setup picks 3.12 automatically."),
    ]),
    ("unzip", "Step 3 · Unzip the kit", [
        ("z1", "Step 3. Unzip the kit.", "Step three. Unzip the kit."),
        ("z2", "In your Downloads folder, right-click powerbi-mcp.zip, choose Extract All… and click Extract.",
               "In your Downloads folder, right-click the power B I MCP zip file, choose, Extract All, and click, Extract."),
        ("z3", "Move the powerbi-mcp folder somewhere permanent, like Documents. Claude Desktop runs it from there, so don't delete it later.",
               "Move the power B I MCP folder somewhere permanent, like Documents. Claude Desktop runs it from there, so don't delete it later."),
    ]),
    ("setup", "Step 4 · Run Setup", [
        ("u1", "Step 4. Run Setup.", "Step four. Run Setup."),
        ("u2", "Open the folder and double-click Setup (Windows).bat",
               "Open the folder and double-click, Setup Windows dot bat."),
        ("u3", "If Windows shows \"Windows protected your PC\", click More info, then Run anyway.",
               "If Windows shows a blue box saying, Windows protected your PC, click More info, then, Run anyway."),
        ("u4", "Wait 1 to 2 minutes while Setup finds Python 3.12, installs the libraries, connects to Claude Desktop and checks everything.",
               "Wait one to two minutes while Setup finds Python 3.12, installs the libraries, connects to Claude Desktop, and checks everything."),
        ("u5", "When every line says OK, you're done. Setup keeps your other Claude servers and backs up the settings file first.",
               "When every line says OK, you're done. Setup keeps your other Claude servers, and backs up the settings file first."),
        ("u6", "Tip: want to see it work before opening Power BI? Double-click Demo test (Windows).bat",
               "Tip: want to see it work before opening Power B I? Double-click, Demo test Windows dot bat."),
    ]),
    ("restart", "Step 5 · Restart Claude Desktop", [
        ("r1", "Step 5. Restart Claude Desktop, fully.", "Step five. Restart Claude Desktop, fully."),
        ("r2", "Closing the window isn't enough. Right-click the Claude icon in the system tray, near the clock, and choose Quit."),
        ("r3", "Then open Claude Desktop again."),
        ("r4", "Go to Settings → Developer. You should see powerbi, running.",
               "Go to Settings, then Developer. You should see power B I, with the status, running."),
    ]),
    ("test", "Step 6 · Open your report and test", [
        ("t1", "Step 6. Open your report and test it.", "Step six. Open your report and test it."),
        ("t2", "Open your .pbix file in Power BI Desktop, and wait until the data has finished loading.",
               "Open your P B I X file in Power B I Desktop, and wait until the data has finished loading."),
        ("t3", "In Claude Desktop, start a new chat and ask: List the tables in my Power BI model"),
        ("t4", "The first time, Claude asks permission to use the tool. Click Always allow."),
        ("t5", "And there it is! Claude lists your tables with their column and measure counts. You're connected."),
        ("t6", "Several reports open? Ask \"Which Power BI reports are open?\" and tell Claude which one to connect to.",
               "Several reports open? Ask, Which Power B I reports are open? Then tell Claude which one to connect to."),
    ]),
    ("ask", "What you can ask", [
        ("a1", "Now you can ask Claude almost anything about your report, in plain English."),
        ("a2", "Explain your data model. Find your top 5 products last quarter. Create a Sales YoY % measure.",
               "Explain your data model. Find your top five products last quarter. Create a sales year over year percent measure."),
        ("a3", "Fix a measure with wrong totals. Find measures nobody uses. Or learn how a DAX formula works, step by step, with your own numbers."),
    ]),
    ("safe", "Editing measures safely", [
        ("e1", "Don't worry about breaking anything."),
        ("e2", "Claude tests every new measure with DAX before saving it. If there's an error, nothing is changed."),
        ("e3", "Changes appear in Power BI Desktop straight away. Save the report to keep them, or close without saving to undo."),
        ("e4", "Claude asks before deleting a measure. And you can always say: don't change anything, only read."),
    ]),
    ("dash", "Step 7 · Let Claude build a dashboard", [
        ("d1", "Now the best part: let Claude build a whole dashboard page."),
        ("d2", "First, save your report as a project, once. In Power BI Desktop: File → Save as → Power BI project (*.pbip).",
               "First, save your report as a project, once. In Power B I Desktop, click File, Save as, and choose, Power B I project, P B I P."),
        ("d3", "Then ask Claude, with the full path to your .pbip file, like this.",
               "Then ask Claude, with the full path to your P B I P file, like this."),
        ("d4", "If Claude adds measures, it asks you to press Ctrl+S. Do it, so they're saved.",
               "If Claude adds measures, it asks you to press Control S. Do it, so they're saved."),
        ("d5", "When Claude says the page is done, close Power BI Desktop and choose Don't save. Saving now would overwrite the new page.",
               "When Claude says the page is done, close Power B I Desktop, and choose, Don't save. Saving now would overwrite the new page."),
        ("d6", "Open the .pbip again, and your new dashboard is right there in the page tabs.",
               "Open the P B I P file again, and your new dashboard is right there in the page tabs."),
    ]),
    ("themes", "Designer themes", [
        ("h1", "Want it to look designed? Add a theme to your request, like \"use the midnight theme\".",
               "Want it to look designed? Add a theme to your request, like, use the midnight theme."),
        ("h2", "There are 8 themes: Corporate, Midnight, Ocean, Sunset, Emerald, Royal, Rose and Graphite. To undo: View → Themes → Default.",
               "There are eight themes: Corporate, Midnight, Ocean, Sunset, Emerald, Royal, Rose, and Graphite. To undo one, go to View, Themes, Default."),
    ]),
    ("samples", "10 sample dashboards to copy", [
        ("m1", "The PDF guide has 10 sample dashboards, each with the exact prompt that made it.",
               "The P D F guide has ten sample dashboards, each with the exact prompt that made it."),
        ("m2", "Sales, profit and loss, HR, marketing, online store, supply chain, hospital, customer support, students and projects."),
        ("m3", "Copy a prompt, change the field names to yours, add your .pbip path, and send it to Claude.",
               "Copy a prompt, change the field names to yours, add your P B I P path, and send it to Claude."),
    ]),
    ("trouble", "Troubleshooting", [
        ("k1", "Something not working? Double-click Check (Windows).bat first. It tests every part and tells you what to fix.",
               "Something not working? Double-click, Check Windows dot bat, first. It tests every part, and tells you what to fix."),
        ("k2", "\"Python 3.12 is not installed\"? Install it, then run Setup again.",
               "Python 3.12 is not installed? Install it, then run Setup again."),
        ("k3", "\"pythonnet failed to load\"? You're on Python 3.13 or newer. Install 3.12, delete the venv folder and run Setup again.",
               "Python net failed to load? You're on Python 3.13 or newer. Install 3.12, delete the V env folder, and run Setup again."),
        ("k4", "Claude has no Power BI tools? It wasn't fully restarted. Quit from the tray icon and open it again.",
               "Claude has no Power B I tools? It wasn't fully restarted. Quit from the tray icon, and open it again."),
        ("k5", "\"No open Power BI report found\"? Open a .pbix and wait for the data to load.",
               "No open Power B I report found? Open a P B I X file, and wait for the data to load."),
        ("k6", "New dashboard page missing? Close Power BI, choose Don't save, and open the .pbip again.",
               "New dashboard page missing? Close Power B I, choose, Don't save, and open the P B I P file again."),
    ]),
    ("extras", "Claude Code, moving and updating", [
        ("x1", "A few extras. If you use Claude Code, Setup adds the server there too."),
        ("x2", "Moved the folder, or got a new version? Just run Setup again."),
    ]),
    ("outro", "You're all set", [
        ("o1", "Still stuck? Email a screenshot of the Check window and your payment ID to groworafoundation@gmail.com. We'll help you get it running.",
               "Still stuck? Email a screenshot of the Check window, and your payment I D, to growora foundation at gmail dot com. We'll help you get it running."),
        ("o2", "That's it! Install Python, unzip, run Setup, restart Claude, open your report, and ask. Happy building!"),
    ]),
]
